FROM python:3.8

WORKDIR /app

COPY master_server.py .
COPY Pipfile* .

RUN apt-get update && apt-get install -y python3-pip && pip3 install virtualenv pipenv
# RUN cd /app && pipenv install

CMD ["python3", "master-server.py"]