FROM python:3.8

WORKDIR /app

COPY worker_server.py .
COPY worker_requirements.txt .

RUN apt-get update && apt-get install -y python3-pip && pip3 install virtualenv pipenv
RUN cd /app && pip install -f worker_requirements.txt

CMD ["python3", "worker-server.py"]